### ISSUE TITLE
安装时提示应用未安装

### ISSUE THREAD

**Issue by wu-vincent** [YiuChoi/Unlock163Music#4]
系统是Cyanogenmod13
安卓6.0

**Comment by YiuChoi** [comment]
应该是签名不一致，先卸载老版本再安装

**Comment by wu-vincent** [comment]
我貌似安装了一个防和谐插件，但不是音量增强器这个名字，是因为这两个包名一样吗？
2016年4月1日 19:12，"YiuChoi" notifications@github.com写道：

**Comment by YiuChoi** [comment]
应该是的

**Comment by 471448446** [comment]
5.0 以上的访客模式，如果在访客里面安装了a.apk。在正常的模式下安装a.apk是安装不了的。

**Comment by wu-vincent** [comment]
@471448446 因为包名一样签名不一样没法安装，已解决。
